# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Compile VeriTabaniSurucu.java
      run: javac VeriTabaniSurucu.java
    - name: Run VeriTabaniSurucu.class
      run: |
        java VeriTabaniSurucu <<EOF
        CREATE TABLE FROM userLogsMini.csv
        SELECT first_name FROM userLogsMini;
        SELECT email FROM userLogsMini WHERE id=2000;
        CREATE TABLE FROM userLogs.csv
        SELECT first_name FROM userLogs;
        SELECT id,first_name,last_name,email FROM userLogs;
        SELECT email FROM userLogs WHERE id=2;
        SELECT email FROM userLogs WHERE first_name=Elfie;
        CREATE TABLE FROM userLogs2.csv
        SELECT first_name FROM userLogs2;
        SELECT id,first_name,last_name,email FROM userLogs2;
        SELECT first_name,last_name,email,gender FROM userLogs2 WHERE id=781;
        SELECT email FROM userLogs2 WHERE first_name=Eamon;
        EOF
